version: "3"

services:
  mysql:
    image: mariadb:10
    container_name: mysql.slim.todo
    stdin_open: true
    tty: true
    networks:
    - global
    env_file:
    - ./docker/mysql/config.env
    volumes:
    - ~/data/mysql.slim.todo:/var/lib/mysql
    restart: always

  php:
    container_name: php.slim.todo
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    networks:
    - global
    stdin_open: true
    tty: true
    env_file:
    - ./.env
    volumes:
    - ./:/opt:cached
    links:
    - mysql
    restart: always

  nginx:
    container_name: nginx.slim.todo
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    networks:
    - global
    stdin_open: true
    tty: true
    labels:
      traefik.frontend.rule: "Host:{subdomain}.slim.test,slim.test"
    volumes:
    - ./public:/opt/public:cached
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    links:
    - php
    restart: always


networks:
  global:
    external: true